export const M4_PERSISTENCE_ENABLED =
  process.env.NEXT_PUBLIC_M4_PERSISTENCE_ENABLED === "true" ||
  process.env.NEXT_PUBLIC_M4_DIAGNOSIS_PERSISTENCE_ENABLED === "true";

export const M4_DIAGNOSIS_PERSISTENCE_ENABLED =
  M4_PERSISTENCE_ENABLED &&
  process.env.NEXT_PUBLIC_M4_DIAGNOSIS_PERSISTENCE_ENABLED === "true";
