export const M4_PERSISTENCE_ENABLED =
  process.env.NEXT_PUBLIC_M4_PERSISTENCE_ENABLED !== "false" &&
  process.env.NEXT_PUBLIC_M4_PERSISTENCE_ENABLED !== "0";

export const M4_DIAGNOSIS_PERSISTENCE_ENABLED =
  M4_PERSISTENCE_ENABLED &&
  process.env.NEXT_PUBLIC_M4_DIAGNOSIS_PERSISTENCE_ENABLED !== "false" &&
  process.env.NEXT_PUBLIC_M4_DIAGNOSIS_PERSISTENCE_ENABLED !== "0";
