import type { AgentRole, ContextPolicy } from "./types";

const COMMON_NEVER = [
  "other-project data",
  "unconfirmed diagnosis candidates as facts",
  "other agents' private working memory",
  "unauthorized material content",
  "hidden chain-of-thought",
] as const;

const policies: Record<AgentRole, ContextPolicy> = {
  CONVERSATION_AGENT: {
    name: "conversation-project-grounding",
    version: "v1",
    agentRole: "CONVERSATION_AGENT",
    always: ["project", "confirmed diagnosis", "conversation summary", "recent messages"],
    optional: ["current section", "open handoffs", "conversation-agent working memory"],
    rag: ["explicitly authorized project materials"],
    never: COMMON_NEVER,
    recentMessageLimit: 16,
    conversationWindow: { recentMessages: 16, rollingSummary: true },
    artifactSelection: ["confirmed outline", "current section metadata", "current manuscript when relevant"],
    totalTokenBudget: 14_000,
    retrievalTokenBudget: 5_000,
    defaultMaterialKinds: ["manuscript", "literature", "requirement", "data", "note"],
    materialPriority: ["requirement", "manuscript", "note", "literature", "data"],
  },
  RESEARCH_PLANNER: {
    name: "research-planning-grounding",
    version: "v1",
    agentRole: "RESEARCH_PLANNER",
    always: ["project", "confirmed diagnosis", "confirmed outline", "confirmed requirements"],
    optional: ["planner working memory", "incoming handoffs", "conversation summary"],
    rag: ["requirements", "literature", "manuscript"],
    never: COMMON_NEVER,
    recentMessageLimit: 10,
    conversationWindow: { recentMessages: 10, rollingSummary: true },
    artifactSelection: ["confirmed outline", "manuscript structure", "research decisions"],
    totalTokenBudget: 16_000,
    retrievalTokenBudget: 7_000,
    defaultMaterialKinds: ["requirement", "literature", "manuscript"],
    materialPriority: ["requirement", "manuscript", "note", "literature"],
  },
  RETRIEVER_EVIDENCE: {
    name: "evidence-retrieval-grounding",
    version: "v1",
    agentRole: "RETRIEVER_EVIDENCE",
    always: ["project", "confirmed diagnosis", "retrieval question"],
    optional: ["current section", "incoming handoffs"],
    rag: ["literature", "manuscript", "data", "requirements"],
    never: COMMON_NEVER,
    recentMessageLimit: 6,
    conversationWindow: { recentMessages: 6, rollingSummary: false },
    artifactSelection: ["retrieval question", "search constraints"],
    totalTokenBudget: 18_000,
    retrievalTokenBudget: 12_000,
    defaultMaterialKinds: ["literature", "manuscript", "data", "requirement"],
    materialPriority: ["literature", "data", "requirement", "manuscript"],
  },
  WRITER: {
    name: "section-writing-grounding",
    version: "v1",
    agentRole: "WRITER",
    always: ["project", "confirmed diagnosis", "confirmed outline", "current section", "latest section version"],
    optional: ["writer working memory", "incoming handoffs", "conversation summary"],
    rag: ["literature", "manuscript", "requirements", "data"],
    never: COMMON_NEVER,
    recentMessageLimit: 8,
    conversationWindow: { recentMessages: 8, rollingSummary: true },
    artifactSelection: ["confirmed outline", "current section", "latest adopted section version"],
    totalTokenBudget: 20_000,
    retrievalTokenBudget: 10_000,
    defaultMaterialKinds: ["literature", "manuscript", "requirement", "data"],
    materialPriority: ["literature", "manuscript", "data", "requirement"],
  },
  REVIEWER: {
    name: "section-review-grounding",
    version: "v1",
    agentRole: "REVIEWER",
    always: ["project", "confirmed diagnosis", "confirmed outline", "current section", "latest section version"],
    optional: ["reviewer working memory", "incoming handoffs", "evidence bindings"],
    rag: ["literature", "requirements", "manuscript"],
    never: COMMON_NEVER,
    recentMessageLimit: 6,
    conversationWindow: { recentMessages: 6, rollingSummary: false },
    artifactSelection: ["current manuscript", "existing evidence bindings"],
    totalTokenBudget: 18_000,
    retrievalTokenBudget: 8_000,
    defaultMaterialKinds: ["literature", "requirement", "manuscript"],
    materialPriority: ["requirement", "literature", "manuscript"],
  },
  VERIFIER: {
    name: "claim-verification-grounding",
    version: "v1",
    agentRole: "VERIFIER",
    always: ["project", "confirmed diagnosis", "claim", "existing evidence bindings"],
    optional: ["current section", "incoming handoffs"],
    rag: ["literature", "data", "requirements", "manuscript"],
    never: COMMON_NEVER,
    recentMessageLimit: 4,
    conversationWindow: { recentMessages: 4, rollingSummary: false },
    artifactSelection: ["claims", "citations", "results", "evidence bindings"],
    totalTokenBudget: 18_000,
    retrievalTokenBudget: 12_000,
    defaultMaterialKinds: ["literature", "data", "requirement", "manuscript"],
    materialPriority: ["literature", "data", "requirement", "manuscript"],
  },
};

export function getContextPolicy(agentRole: AgentRole): ContextPolicy {
  return policies[agentRole];
}

export const CONTEXT_POLICIES = policies;
